-- ============================================================================
-- Bayele — seed (production launch: intentionally empty).
-- ============================================================================
-- The pre-launch demo talent seed (12 fabricated creator/consultant profiles with
-- `demo_*@bayele.app` identities and fixed a0000000-/b0000000- UUIDs) has been RETIRED.
--
-- Why: at launch the public marketplace must show ONLY real, onboarded, admin-approved
-- profiles. Seeding fake talent into a live directory is demo content — removed on
-- 2026-09-02 both from this file and from the production database.
--
-- This file is deliberately a no-op so that `supabase db reset` / `supabase start` never
-- re-introduces demo data. If you need sample data for LOCAL development only, restore the
-- previous version from git history (it is idempotent and safe on a local stack) — but do
-- NOT apply it to any shared/staging/production project.
-- ============================================================================

-- (no seed rows)
